### ISSUE TITLE
Incompatibility with Flarum Blog Extension

### ISSUE THREAD

**Issue by iamdarkle** [android-com-pl/my-tags#1] opened 2021-07-17 17:07 UTC
There is a bug that cuts off the blog categories when activating this extension.

With the extension activated:
![msedge_38wammiiXx](https://user-images.githubusercontent.com/15818451/126044570-d8b5d87a-80b6-4af9-8efc-645054827b69.png)
Without the extension activated:
![msedge_TsfSCrvVUE](https://user-images.githubusercontent.com/15818451/126044573-15583210-e55b-42af-aea3-bbcdbe07d2b3.png)

**Comment by rafaucau** [comment] 2021-07-19 08:36
@iamdarkle I can't reproduce it. Flarum Blog Extension does not load all the tags even when I turn off My Tags.
It only loads all of them when I go to the tags page first and then to the blogs page.

It looks to me like a problem with the Blogs extension itself

**Comment by rafaucau** [comment] 2021-07-19 08:44
It looks to me like a problem with the Blogs extension itself

**Comment by rafaucau** [comment] 2021-08-11 18:11
I am closing this issue for now. If you have more information, you can open it

**Closed as completed by rafaucau** 2021-08-11 18:11 UTC
Labels: bug

**Comment by iamdarkle** [comment] 2021-08-20 21:09
@rafaucau Thanks 1.1.1 did fix it, sorry I forgot this, I had planned to do some testing to find out what caused this bug, but I kept putting it off until I completely forgot. Thank you very much!
